/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCadRouteImport } from './routes/_authenticated.cad'
import { Route as AuthDiscordRouteImport } from './routes/auth.discord'
import { Route as AuthenticatedCadIndexRouteImport } from './routes/_authenticated.cad.index'
import { Route as AuthenticatedCadBolosRouteImport } from './routes/_authenticated.cad.bolos'
import { Route as AuthenticatedCadDispatchRouteImport } from './routes/_authenticated.cad.dispatch'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'
import { Route as ApiPublicDiscordStartRouteImport } from './routes/api/public/discord/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCadRoute = AuthenticatedCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthDiscordRoute = AuthDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedCadIndexRoute = AuthenticatedCadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCadRoute,
} as any)
const AuthenticatedCadBolosRoute = AuthenticatedCadBolosRouteImport.update({
  id: '/bolos',
  path: '/bolos',
  getParentRoute: () => AuthenticatedCadRoute,
} as any)
const AuthenticatedCadDispatchRoute =
  AuthenticatedCadDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => AuthenticatedCadRoute,
  } as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordStartRoute = ApiPublicDiscordStartRouteImport.update({
  id: '/api/public/discord/start',
  path: '/api/public/discord/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cad': typeof AuthenticatedCadRouteWithChildren
  '/auth/discord': typeof AuthDiscordRoute
  '/cad/bolos': typeof AuthenticatedCadBolosRoute
  '/cad/dispatch': typeof AuthenticatedCadDispatchRoute
  '/cad/': typeof AuthenticatedCadIndexRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/start': typeof ApiPublicDiscordStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/discord': typeof AuthDiscordRoute
  '/cad/bolos': typeof AuthenticatedCadBolosRoute
  '/cad/dispatch': typeof AuthenticatedCadDispatchRoute
  '/cad': typeof AuthenticatedCadIndexRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/start': typeof ApiPublicDiscordStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/cad': typeof AuthenticatedCadRouteWithChildren
  '/auth/discord': typeof AuthDiscordRoute
  '/_authenticated/cad/bolos': typeof AuthenticatedCadBolosRoute
  '/_authenticated/cad/dispatch': typeof AuthenticatedCadDispatchRoute
  '/_authenticated/cad/': typeof AuthenticatedCadIndexRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/start': typeof ApiPublicDiscordStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cad'
    | '/auth/discord'
    | '/cad/bolos'
    | '/cad/dispatch'
    | '/cad/'
    | '/api/public/discord/callback'
    | '/api/public/discord/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/discord'
    | '/cad/bolos'
    | '/cad/dispatch'
    | '/cad'
    | '/api/public/discord/callback'
    | '/api/public/discord/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cad'
    | '/auth/discord'
    | '/_authenticated/cad/bolos'
    | '/_authenticated/cad/dispatch'
    | '/_authenticated/cad/'
    | '/api/public/discord/callback'
    | '/api/public/discord/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicDiscordStartRoute: typeof ApiPublicDiscordStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cad': {
      id: '/_authenticated/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AuthenticatedCadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/discord': {
      id: '/auth/discord'
      path: '/discord'
      fullPath: '/auth/discord'
      preLoaderRoute: typeof AuthDiscordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/cad/': {
      id: '/_authenticated/cad/'
      path: '/'
      fullPath: '/cad/'
      preLoaderRoute: typeof AuthenticatedCadIndexRouteImport
      parentRoute: typeof AuthenticatedCadRoute
    }
    '/_authenticated/cad/bolos': {
      id: '/_authenticated/cad/bolos'
      path: '/bolos'
      fullPath: '/cad/bolos'
      preLoaderRoute: typeof AuthenticatedCadBolosRouteImport
      parentRoute: typeof AuthenticatedCadRoute
    }
    '/_authenticated/cad/dispatch': {
      id: '/_authenticated/cad/dispatch'
      path: '/dispatch'
      fullPath: '/cad/dispatch'
      preLoaderRoute: typeof AuthenticatedCadDispatchRouteImport
      parentRoute: typeof AuthenticatedCadRoute
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/start': {
      id: '/api/public/discord/start'
      path: '/api/public/discord/start'
      fullPath: '/api/public/discord/start'
      preLoaderRoute: typeof ApiPublicDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCadRouteChildren {
  AuthenticatedCadBolosRoute: typeof AuthenticatedCadBolosRoute
  AuthenticatedCadDispatchRoute: typeof AuthenticatedCadDispatchRoute
  AuthenticatedCadIndexRoute: typeof AuthenticatedCadIndexRoute
}

const AuthenticatedCadRouteChildren: AuthenticatedCadRouteChildren = {
  AuthenticatedCadBolosRoute: AuthenticatedCadBolosRoute,
  AuthenticatedCadDispatchRoute: AuthenticatedCadDispatchRoute,
  AuthenticatedCadIndexRoute: AuthenticatedCadIndexRoute,
}

const AuthenticatedCadRouteWithChildren =
  AuthenticatedCadRoute._addFileChildren(AuthenticatedCadRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCadRoute: typeof AuthenticatedCadRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCadRoute: AuthenticatedCadRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthDiscordRoute: typeof AuthDiscordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDiscordRoute: AuthDiscordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicDiscordStartRoute: ApiPublicDiscordStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
