/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCadRouteImport } from './routes/_authenticated.cad'
import { Route as AuthenticatedCadIndexRouteImport } from './routes/_authenticated.cad.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCadRoute = AuthenticatedCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadIndexRoute = AuthenticatedCadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cad': typeof AuthenticatedCadRouteWithChildren
  '/cad/': typeof AuthenticatedCadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cad': typeof AuthenticatedCadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cad': typeof AuthenticatedCadRouteWithChildren
  '/_authenticated/cad/': typeof AuthenticatedCadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/cad' | '/cad/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/cad'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cad'
    | '/_authenticated/cad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cad': {
      id: '/_authenticated/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof AuthenticatedCadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cad/': {
      id: '/_authenticated/cad/'
      path: '/'
      fullPath: '/cad/'
      preLoaderRoute: typeof AuthenticatedCadIndexRouteImport
      parentRoute: typeof AuthenticatedCadRoute
    }
  }
}

interface AuthenticatedCadRouteChildren {
  AuthenticatedCadIndexRoute: typeof AuthenticatedCadIndexRoute
}

const AuthenticatedCadRouteChildren: AuthenticatedCadRouteChildren = {
  AuthenticatedCadIndexRoute: AuthenticatedCadIndexRoute,
}

const AuthenticatedCadRouteWithChildren =
  AuthenticatedCadRoute._addFileChildren(AuthenticatedCadRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCadRoute: typeof AuthenticatedCadRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCadRoute: AuthenticatedCadRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
